### ISSUE TITLE
Need better render option for BYU ACME PDF docs

### ISSUE THREAD

**Issue by rickecon** [OpenRG/UN-OG-Training#11]
We use the BYU Applied and Computational Math Emphasis open access Python labs in these training materials. We link to their [2021-2022 materials](https://acme.byu.edu/2021-2022-materials/) because those labs are individually packaged and the PDF format displays separately for each of them. It is a little less easy to use the most recent 2023-2024 materials, which are packaged as multi-chapter single PDF files ([here](https://acme.byu.edu/00000188-dfac-d222-a7ea-dffd5efc0001/junior-labs-summer) and [here](https://acme.byu.edu/00000188-dfad-dabf-a5b9-dfad387b0001/senior-labs-summer)) that have to be downloaded as `.zip` files that the students would have to search through. The updates to the 2023-2024 materials are fairly small, but they are significant in some places (e.g., discussion of fstrings in Exceptions and file I/O chapter). Below are some options of what we can do.

1. Current approach. Link to 2021-2021 labs and add supplementary exercises and content for areas that need to be updated.
2. Link to 2023-2024 labs and just have our users download the `.zip` files and search through to the correct chapters
3. Save the individual PDF files somewhere like Google Drive where they can be pulled up as full PDF files in users' browser.
4. Rewrite each ACME lab as is but as a `.md` file that can be rendered in the Jupyter Book. This is what the ACME labs should transition to anyway. Maybe this would help them.
5. Write our own `.md` training content and exercises.

cc: @jdebacker

**Comment by jdebacker** [comment]
Resolved via `iFrames` introduced in PR #23
