### ISSUE TITLE
Missing Chapter 16 in the OG-Core Training Material

### ISSUE THREAD

**Issue by sezdi0810** [OpenRG/UN-OG-Training#45]
Thanks for filing an issue! Please remove any top-level headers that do not apply.

After working through Chapter 15 (Simulating OG-Core), I was unable to work through any of the code in Chapter 17 (OG-Core Output). I think this may be due to the missing chapter in the training material, i.e., Chapter 16. 

Thank you.

**Comment by SeaCelo** [comment]
@sezdi0810 

At the bottom of chapter 15 there is a section numbered 16: [16. Exercises:](https://www.openrg.com/UN-OG-Training/OG/Simulation.html#exercises). Is this sufficient? If so, it should be listed in the outline.

**Comment by sezdi0810** [comment]
I tried the Exercise at the bottom of Chapter 15 (Exercise 16.1). I think it is a practice question for the tutorial in Chapter 15. After the Exercise I tried running the first block of code in Chapter 17:
     p = Specifications(
        baseline=True,
        num_workers=num_workers,
        baseline_dir="C:\User\OG-Core\Simulation24\Baseline",
        output_base="C:\User\OG-Core\Simulation24\Baseline",
    )

I got the following error:
baseline_dir="C:\User\OG-Core\Simulation24\Baseline",              
                                                                                                    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

I also checked my computer and saw that the paths in lines 4 and 5 of the code do not exist.

Thank you.

**Comment by jdebacker** [comment]
@sezdi0810 Thanks for raising this issue.

I think there are two things to be addresses:
1. Chapter numbering is inconsistent (it skips 16)
2. We should be more clear that the code block you copied is just an example and not intended to be copy and pasted).  I think the code block just before Exercise 16.1 should work (but please confirm- it might have issues on a Windows machine) and is intended to by copy and pasted (as Exercises 16.1 asks you to do).

**Comment by sezdi0810** [comment]
Thank you for the clarification. The code block before Exercise 16.1 works (copy/paste) on a mac with lower case "cit".

**Comment by jdebacker** [comment]
This issue was addressed in PR #47
