### ISSUE TITLE
Minor code typo in Chapter 15

### ISSUE THREAD

**Issue by sezdi0810** [OpenRG/UN-OG-Training#46]
Thanks for filing an issue! Please remove any top-level headers that do not apply.

There was a minor typo in the second block of code for Chapter 15 (Simulating OG-Core), which prevented the code from running:
....
p_reform.update_specifications({'CIT_rate': [[0.15]]})
....

When I changed CIT to lower case, the code worked.

**Comment by jdebacker** [comment]
Addressed in PR #41
