### ISSUE TITLE
Error with glue command in section 16

### ISSUE THREAD

**Issue by sezdi0810** [OpenRG/UN-OG-Training#48]
There was a problem in running the glue command in 16.3.1 and 16.3.2. In the last line of the command for tabular output and plotting output the glue command does not work. 

Specifically, these are the commands that do not work for each block of code, respectively:
(i) glue(table.to_markdown())
(ii) glue(fig.show())

The problem can be partially resolved by:
(i)  installing the glue package: "conda install myst-nb" 
(ii) importing the glue package: "from myst-nb import glue 

However, the glue command still gives the following error in both blocks of code: 
"NameError: name 'glue' is not defined"

Thank you.

**Comment by SeaCelo** [comment]
@sezdi0810 I get a slightly different error:
`TypeError: glue() missing 1 required positional argument: 'variable' `

**Comment by jdebacker** [comment]
@sezdi0810 Thanks for raising this issue.  I was unable to replicate the error you found.

But I just merged PR #49, which should address the issue noted by @SeaCelo.

If you can rebuild your `un-og-training-dev` environment and then try to compile the book again, please let me know if you run into any errors.  Thanks!
