### ISSUE TITLE
Exercise 16.2 fails due to wrong dimensions

### ISSUE THREAD

**Issue by SeaCelo** [OpenRG/UN-OG-Training#50]
On step [16.2](https://www.openrg.com/UN-OG-Training/OG/Output.html#interpreting-og-core-output) the calculation of `non_stationary_Y` fails because the two variables have different dimensions.

```
non_stationary_Y = TPI_vars["Y"] * np.cumprod(1 + p.g_n) * np.exp(p.g_y * np.arange(p.T))
print(non_stationary_Y
```

gives the error: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 1
----> 1 non_stationary_Y = TPI_vars["Y"] * np.cumprod(1 + p.g_n) * np.exp(p.g_y * np.arange(p.T))
      2 print(non_stationary_Y)

ValueError: operands could not be broadcast together with shapes (320,) (400,) 
```
The dimensions are:
`TPI_vars["Y"].shape` = `(320,)`
`p.g_n.shape` = `(400,)`

This breaks exercise 16.2. 

cc: @sezdi0810 @gubenda

**Comment by jdebacker** [comment]
Thanks for the report @SeaCelo. 

This had to do with recent changes in OG-Core and we'll get the docs here updated with the latest versions soon.
